from .get_N_LGR import obtener_N_LGR
from .mc_estabilidad_b import mc_estabilidad_b
from .mc_max_N_log10 import mc_maximo_N_log10
from .mc_max_curv import mc_maxima_curvatura
from .mc_menor_pend import mc_menor_pendiente
from .get_grl_values_noise import get_GutenbergRichter_values_noised
from .get_grl_values import get_GutenbergRichter_values
from .get_grl_values_boost import get_GutenbergRichter_values_boosted
